import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';

export const BlogPostPage: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const [content, setContent] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // For a Vite SPA, we can dynamically fetch the raw markdown file from the public folder 
    // or import it if configured. Assuming it's served statically for now:
    fetch(`/content/blog/${slug}.md`)
      .then((res) => {
        if (!res.ok) throw new Error('Post not found');
        return res.text();
      })
      .then((text) => {
        // Strip the frontmatter for simple rendering (basic regex)
        const contentWithoutFrontmatter = text.replace(/---[\s\S]*?---/, '');
        setContent(contentWithoutFrontmatter);
        setIsLoading(false);
      })
      .catch((err) => {
        setContent('# 404 - Post not found');
        setIsLoading(false);
      });
  }, [slug]);

  if (isLoading) return <div className="text-white text-center py-12">Loading...</div>;

  return (
    <div className="max-w-3xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="mb-8">
        <Link to="/blog" className="text-blue-500 hover:text-blue-400 text-sm">
          &larr; Back to all posts
        </Link>
      </div>
      
      {/* The 'prose' class comes from @tailwindcss/typography and handles styling all standard HTML elements generated by markdown */}
      <article className="prose prose-invert prose-blue max-w-none">
        <ReactMarkdown>{content}</ReactMarkdown>
      </article>
    </div>
  );
};